// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVayzwHrtYtVY1xKeRI2QGRrsyGavj8f0',
    appId: '1:699038433397:web:bc65f3f98be91e06cbb83c',
    messagingSenderId: '699038433397',
    projectId: 'zakker-a',
    authDomain: 'zakker-a.firebaseapp.com',
    storageBucket: 'zakker-a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBwYAeTT8sHuumCyq238T7GRwApRSTsyk',
    appId: '1:699038433397:android:feffe35c8b0d3fa1cbb83c',
    messagingSenderId: '699038433397',
    projectId: 'zakker-a',
    storageBucket: 'zakker-a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD92fIsR0f-tyDpT75F58d0flkNFqWQccA',
    appId: '1:699038433397:ios:ebed0e17d1d9d325cbb83c',
    messagingSenderId: '699038433397',
    projectId: 'zakker-a',
    storageBucket: 'zakker-a.appspot.com',
    iosClientId: '699038433397-0pbiv0hci0bgmccdajanm3daff4kgi1g.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD92fIsR0f-tyDpT75F58d0flkNFqWQccA',
    appId: '1:699038433397:ios:ebed0e17d1d9d325cbb83c',
    messagingSenderId: '699038433397',
    projectId: 'zakker-a',
    storageBucket: 'zakker-a.appspot.com',
    iosClientId: '699038433397-0pbiv0hci0bgmccdajanm3daff4kgi1g.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
